#!/usr/bin/env python3
"""Convert markdown reports to standalone HTML pages and update the index.

Scans docs/reports/ for *.md files, converts each to a self-contained HTML
page with dark theme and Mermaid chart rendering, and updates docs/index.html.
"""

import os
import re
import sys
from html import escape as html_escape

REPORTS_DIR = "docs/reports"
INDEX_FILE = "docs/index.html"

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        :root {{
            --bg: #0d1117;
            --surface: #161b22;
            --border: #30363d;
            --text: #e6edf3;
            --text-muted: #8b949e;
            --accent: #58a6ff;
            --green: #3fb950;
        }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
            background: var(--bg); color: var(--text); line-height: 1.6;
        }}
        .container {{ max-width: 960px; margin: 0 auto; padding: 2rem 1.5rem; }}
        .back {{ display: inline-block; color: var(--accent); text-decoration: none; margin-bottom: 1.5rem; }}
        h1 {{ font-size: 1.75rem; margin-bottom: 0.5rem; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }}
        h2 {{ font-size: 1.3rem; margin: 2rem 0 0.75rem; color: var(--accent); }}
        h3 {{ font-size: 1.1rem; margin: 1.5rem 0 0.5rem; }}
        blockquote {{ color: var(--text-muted); border-left: 3px solid var(--border); padding-left: 1rem; margin: 0.5rem 0 1rem; }}
        table {{ border-collapse: collapse; width: 100%; margin: 0.75rem 0; }}
        th, td {{ border: 1px solid var(--border); padding: 0.5rem 0.75rem; text-align: left; font-size: 0.9rem; }}
        th {{ background: var(--surface); }}
        tr:nth-child(even) {{ background: var(--surface); }}
        a {{ color: var(--accent); text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        pre {{ background: var(--surface); padding: 1rem; border-radius: 6px; overflow-x: auto; margin: 1rem 0; }}
        code {{ font-family: 'SFMono-Regular', Consolas, monospace; font-size: 0.9em; }}
        .mermaid {{ background: var(--surface); padding: 1.5rem; border-radius: 6px; margin: 1rem 0; text-align: center; }}
        footer {{ text-align: center; padding: 2rem 0; margin-top: 2rem; border-top: 1px solid var(--border); color: var(--text-muted); font-size: 0.85rem; }}
    </style>
</head>
<body>
    <div class="container">
        <a class="back" href="../index.html">← All Reports</a>
        {content}
        <footer>Generated by gh-work-report</footer>
    </div>
    <script type="module">
        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
        mermaid.initialize({{ startOnLoad: true, theme: 'dark' }});
    </script>
</body>
</html>
"""


def md_to_html(md: str) -> str:
    """Minimal markdown-to-HTML converter. Handles the subset we generate."""
    lines = md.split("\n")
    html_lines: list[str] = []
    in_table = False
    in_mermaid = False
    mermaid_lines: list[str] = []
    in_code = False
    code_lines: list[str] = []

    for line in lines:
        stripped = line.strip()

        # Mermaid blocks
        if stripped == "```mermaid":
            in_mermaid = True
            mermaid_lines = []
            continue
        if in_mermaid and stripped == "```":
            in_mermaid = False
            html_lines.append(f'<div class="mermaid">\n{"chr(10)".join(mermaid_lines)}\n</div>')
            # Use actual newline character
            html_lines[-1] = '<div class="mermaid">\n' + "\n".join(mermaid_lines) + "\n</div>"
            continue
        if in_mermaid:
            mermaid_lines.append(html_escape(stripped))
            continue

        # Code blocks
        if stripped.startswith("```") and not in_code:
            in_code = True
            code_lines = []
            continue
        if in_code and stripped == "```":
            in_code = False
            html_lines.append(f'<pre><code>{"<br>".join(code_lines)}</code></pre>')
            continue
        if in_code:
            code_lines.append(html_escape(line))
            continue

        # Table separator
        if re.match(r"^\|[-| :]+\|$", stripped):
            continue

        # Table rows
        if stripped.startswith("|") and stripped.endswith("|"):
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            if not in_table:
                in_table = True
                html_lines.append("<table>")
                html_lines.append("<thead><tr>" + "".join(f"<th>{inline(c)}</th>" for c in cells) + "</tr></thead>")
                html_lines.append("<tbody>")
            else:
                html_lines.append("<tr>" + "".join(f"<td>{inline(c)}</td>" for c in cells) + "</tr>")
            continue
        elif in_table:
            in_table = False
            html_lines.append("</tbody></table>")

        # Headings
        m = re.match(r"^(#{1,3})\s+(.+)$", stripped)
        if m:
            level = len(m.group(1))
            html_lines.append(f"<h{level}>{inline(m.group(2))}</h{level}>")
            continue

        # Blockquote
        if stripped.startswith("> "):
            html_lines.append(f"<blockquote>{inline(stripped[2:])}</blockquote>")
            continue

        # Empty line
        if not stripped:
            continue

        # Paragraph
        html_lines.append(f"<p>{inline(stripped)}</p>")

    if in_table:
        html_lines.append("</tbody></table>")

    return "\n".join(html_lines)


def inline(text: str) -> str:
    """Convert inline markdown (links, bold, code) to HTML."""
    # Links: [text](url)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    # Bold: **text**
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    # Inline code: `text`
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    # Emoji shortcuts (common ones)
    text = text.replace("✅", "✅").replace("❌", "❌").replace("🔵", "🔵")
    return text


def convert_reports():
    """Convert all .md reports to .html and update the index."""
    if not os.path.isdir(REPORTS_DIR):
        print(f"No reports directory: {REPORTS_DIR}", file=sys.stderr)
        return

    reports = []
    for fname in sorted(os.listdir(REPORTS_DIR), reverse=True):
        if not fname.endswith(".md"):
            continue

        md_path = os.path.join(REPORTS_DIR, fname)
        html_fname = fname.replace(".md", ".html")
        html_path = os.path.join(REPORTS_DIR, html_fname)

        with open(md_path) as f:
            md = f.read()

        title_match = re.search(r"^#\s+(.+)$", md, re.MULTILINE)
        title = title_match.group(1) if title_match else fname

        content = md_to_html(md)
        html = HTML_TEMPLATE.format(title=html_escape(title), content=content)

        with open(html_path, "w") as f:
            f.write(html)
        print(f"  Converted {fname} → {html_fname}", file=sys.stderr)

        date_match = re.search(r"report-(\d{4}-\d{2}-\d{2})-to-(\d{4}-\d{2}-\d{2})", fname)
        if date_match:
            reports.append((date_match.group(1), date_match.group(2), html_fname))

    update_index(reports)


def update_index(reports: list[tuple[str, str, str]]):
    if not os.path.isfile(INDEX_FILE):
        print(f"No index file: {INDEX_FILE}", file=sys.stderr)
        return

    with open(INDEX_FILE) as f:
        html = f.read()

    if reports:
        items = "\n".join(
            f'                <li><a href="reports/{fname}">{start} → {end}</a></li>'
            for start, end, fname in reports
        )
    else:
        items = '                <li class="empty-state">No reports yet — reports will appear here after the first workflow run.</li>'

    html = re.sub(
        r"(<!-- REPORT_LIST_START -->).*?(<!-- REPORT_LIST_END -->)",
        rf"\1\n{items}\n                \2",
        html,
        flags=re.DOTALL,
    )

    with open(INDEX_FILE, "w") as f:
        f.write(html)
    print(f"  Updated {INDEX_FILE}", file=sys.stderr)


if __name__ == "__main__":
    convert_reports()
